# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_category_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'General Site Data',
                'verbose_name_plural': 'General Site Data',
            },
        ),
    ]
