# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLogoInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('logo_count', models.IntegerField(default=0, verbose_name='Logo PPV Count')),
                ('logo_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('logo_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('total_logo_count', models.IntegerField(default=0, verbose_name='Total Count (PPV)')),
                ('user_total_due', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
            ],
            options={
                'verbose_name': 'Business Logo Invoice',
                'verbose_name_plural': 'Business Logo Invoices',
            },
        ),
        migrations.CreateModel(
            name='EmbedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('embed_count', models.IntegerField(blank=True, null=True, verbose_name='Embed Count')),
                ('embed_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('skigit_embed_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('embed_total_count', models.IntegerField(blank=True, null=True, verbose_name='Total Count')),
                ('embed_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
            ],
            options={
                'verbose_name': 'Embed Invoice',
                'verbose_name_plural': 'Embed Invoices',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('customer_id', models.CharField(max_length=100, verbose_name='Customer id')),
                ('customer_location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Location')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('payment_method_token', models.CharField(max_length=300, verbose_name='Customer token')),
                ('c_image_url', models.URLField(blank=True, null=True, verbose_name='Card Type Image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='PayPal Email')),
                ('billing_agreement_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Agreement ID')),
                ('last_4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last 4 Numbers')),
                ('first_6', models.PositiveIntegerField(blank=True, null=True, verbose_name='first 6 Numbers (bin)')),
                ('cardholder_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Card Holder Name')),
                ('debit', models.CharField(blank=True, max_length=300, null=True, verbose_name='Debit')),
                ('issuing_bank', models.CharField(blank=True, max_length=250, null=True, verbose_name='Issuing Bank')),
                ('country_of_issuance', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country of Issuance')),
                ('card_status', models.CharField(blank=True, max_length=250, null=True, verbose_name='Card Status')),
                ('cvv_response_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CVV Response Code')),
                ('currency_iso_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency iso Code')),
                ('credit_card_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit/Debit Card Type')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Credit Card/ PayPal Account Deleted')),
                ('merchant_account_id', models.URLField(blank=True, null=True, verbose_name='Merchant Account id')),
                ('unique_number_identifier', models.CharField(blank=True, max_length=500, null=True, verbose_name='Unique Identifier Number')),
                ('processor_response_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='Processor Response Code')),
            ],
            options={
                'verbose_name': 'Invoice Vault',
                'verbose_name_plural': 'Invoices Vault',
            },
        ),
        migrations.CreateModel(
            name='InvoiceBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Payable Amount')),
                ('payed_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Payed Amount')),
                ('payment_status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Payed')], default=False, verbose_name='Payment Received')),
                ('pay_method', models.CharField(choices=[('0', 'PayPalAccount'), ('1', 'CreditCard')], default='0', max_length=5, verbose_name='Payment Method')),
                ('pay_mnth', models.CharField(max_length=2, verbose_name='Pay Month')),
                ('pay_yr', models.CharField(max_length=4, verbose_name='Pay Year')),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction id')),
            ],
            options={
                'verbose_name': 'Billing Info',
                'verbose_name_plural': 'Billing Info',
            },
        ),
        migrations.CreateModel(
            name='PluginInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('plugin_count', models.IntegerField(blank=True, default=0, verbose_name='Plugin Count')),
                ('current_plugin_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('plugin_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('plugin_total_count', models.IntegerField(blank=True, default=0, verbose_name='Total Count')),
                ('plug_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
            ],
            options={
                'verbose_name': 'Plugin Invoice',
                'verbose_name_plural': 'Plugin Invoices',
            },
        ),
        migrations.CreateModel(
            name='PostInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='Post Count')),
                ('skigit_post_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('post_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('post_total_count', models.IntegerField(blank=True, null=True, verbose_name='Total Count')),
                ('social_network_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Social Network Type')),
                ('post_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
            ],
            options={
                'verbose_name': 'Post Invoice',
                'verbose_name_plural': 'Post Invoices',
            },
        ),
        migrations.CreateModel(
            name='ShareInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('share_count', models.IntegerField(blank=True, null=True, verbose_name='Share Count')),
                ('share_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('skigit_share_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('total_share_count', models.IntegerField(blank=True, null=True, verbose_name='Total Count')),
                ('share_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Share Invoice',
                'verbose_name_plural': 'Share Invoices',
            },
        ),
        migrations.CreateModel(
            name='VisitCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('logo_charge', models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Logo PPV Charge')),
                ('link_charge', models.DecimalField(blank=True, decimal_places=2, default=1.99, max_digits=9, verbose_name='Web Link Charge')),
                ('plug_charge', models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Plugin Charge')),
                ('post_charge', models.DecimalField(blank=True, decimal_places=2, default=0.79, max_digits=9, verbose_name='Post Charge')),
                ('share_charge', models.DecimalField(blank=True, decimal_places=2, default=0.49, max_digits=9, verbose_name='Share Charge')),
                ('embed_charge', models.DecimalField(blank=True, decimal_places=2, default=49.0, max_digits=9, verbose_name='Embed Charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuse_payment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Business Charge',
                'verbose_name_plural': 'Business Charges',
            },
        ),
        migrations.CreateModel(
            name='WebLinkInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('web_link', models.URLField(blank=True, null=True, verbose_name='Awesome Company Links')),
                ('link_count', models.IntegerField(default=0, verbose_name='Links Count')),
                ('link_due_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)')),
                ('link_total_due', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)')),
                ('link_total_count', models.IntegerField(default=0, verbose_name='Total Count')),
                ('link_is_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_visitor_user', to=settings.AUTH_USER_MODEL, verbose_name='Business User')),
                ('web_link_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_link_user', to=settings.AUTH_USER_MODEL, verbose_name='Web Link User')),
            ],
            options={
                'verbose_name': 'Awesome Web link Invoice',
                'verbose_name_plural': 'Awesome Web link Invoices',
            },
        ),
    ]
