# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslogoinvoice',
            options={'verbose_name': 'Business Logo Invoice', 'verbose_name_plural': 'Business Logo Invoices'},
        ),
        migrations.AlterModelOptions(
            name='embedinvoice',
            options={'verbose_name': 'Embed Invoice', 'verbose_name_plural': 'Embed Invoices'},
        ),
        migrations.AlterModelOptions(
            name='plugininvoice',
            options={'verbose_name': 'Plugin Invoice', 'verbose_name_plural': 'Plugin Invoices'},
        ),
        migrations.AlterModelOptions(
            name='postinvoice',
            options={'verbose_name': 'Post Invoice', 'verbose_name_plural': 'Post Invoices'},
        ),
        migrations.AlterModelOptions(
            name='shareinvoice',
            options={'verbose_name': 'Share Invoice', 'verbose_name_plural': 'Share Invoices'},
        ),
        migrations.AlterModelOptions(
            name='visitcharges',
            options={'verbose_name': 'Business Charge', 'verbose_name_plural': 'Business Charges'},
        ),
        migrations.AlterModelOptions(
            name='weblinkinvoice',
            options={'verbose_name': 'Awesome Web link Invoice', 'verbose_name_plural': 'Awesome Web link Invoices'},
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_count',
            field=models.IntegerField(default=0, verbose_name='Logo PPV Count'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='total_logo_count',
            field=models.IntegerField(default=0, verbose_name='Total Count (PPV)'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='user_total_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Embed Count'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='skigit_embed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='current_plugin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plug_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Plugin Count'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_total_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post Count'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='skigit_post_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='social_network_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Social Network Type'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Share Count'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='skigit_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='total_share_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='embed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=49.0, max_digits=9, verbose_name='Embed Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='link_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.99, max_digits=9, verbose_name='Web Link Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='logo_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Logo PPV Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='plug_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Plugin Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='post_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.79, max_digits=9, verbose_name='Post Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='share_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.49, max_digits=9, verbose_name='Share Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuse_payment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_count',
            field=models.IntegerField(default=0, verbose_name='Links Count'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_total_count',
            field=models.IntegerField(default=0, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_total_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_visitor_user', to=settings.AUTH_USER_MODEL, verbose_name='Business User'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='web_link',
            field=models.URLField(blank=True, null=True, verbose_name='Awesome Company Links'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='web_link_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_link_user', to=settings.AUTH_USER_MODEL, verbose_name='Web Link User'),
        ),
    ]
