# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0004_auto_20170627_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslogoinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='businesslogoinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='embedinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='embedinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='invoicebilling',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='invoicebilling',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='shareinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_count',
            field=models.IntegerField(default=0, verbose_name='Logo PPV Count'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='logo_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='total_logo_count',
            field=models.IntegerField(default=0, verbose_name='Total Count (PPV)'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='businesslogoinvoice',
            name='user_total_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Embed Count'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='embed_total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='skigit_embed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='embedinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_agreement_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Agreement ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='c_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Card Type Image'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='card_status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Card Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Card Holder Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='country_of_issuance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Country of Issuance'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_card_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit/Debit Card Type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency_iso_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency iso Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_id',
            field=models.CharField(max_length=100, verbose_name='Customer id'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Location'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cvv_response_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CVV Response Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='debit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PayPal Email'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='first_6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='first 6 Numbers (bin)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Credit Card/ PayPal Account Deleted'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issuing_bank',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Issuing Bank'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_4',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last 4 Numbers'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='merchant_account_id',
            field=models.URLField(blank=True, null=True, verbose_name='Merchant Account id'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method_token',
            field=models.CharField(max_length=300, verbose_name='Customer token'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor_response_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Processor Response Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unique_number_identifier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Unique Identifier Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Payable Amount'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='pay_method',
            field=models.CharField(choices=[('0', 'PayPalAccount'), ('1', 'CreditCard')], default='0', max_length=5, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='pay_mnth',
            field=models.CharField(max_length=2, verbose_name='Pay Month'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='pay_yr',
            field=models.CharField(max_length=4, verbose_name='Pay Year'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='payed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Payed Amount'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='payment_status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Payed')], default=False, verbose_name='Payment Received'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction id'),
        ),
        migrations.AlterField(
            model_name='invoicebilling',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='current_plugin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plug_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Plugin Count'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='plugin_total_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='plugininvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post Count'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='post_total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='skigit_post_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='social_network_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Social Network Type'),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Share Count'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='share_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='skigit_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='total_share_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='shareinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='embed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=49.0, max_digits=9, verbose_name='Embed Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='link_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.99, max_digits=9, verbose_name='Web Link Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='logo_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Logo PPV Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='plug_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.29, max_digits=9, verbose_name='Plugin Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='post_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.79, max_digits=9, verbose_name='Post Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='share_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.49, max_digits=9, verbose_name='Share Charge'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='visitcharges',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuse_payment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_count',
            field=models.IntegerField(default=0, verbose_name='Links Count'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_is_paid',
            field=models.BooleanField(default=False, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_total_count',
            field=models.IntegerField(default=0, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='link_total_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Due Amount($)'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_visitor_user', to=settings.AUTH_USER_MODEL, verbose_name='Business User'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='web_link',
            field=models.URLField(blank=True, null=True, verbose_name='Awesome Company Links'),
        ),
        migrations.AlterField(
            model_name='weblinkinvoice',
            name='web_link_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_link_user', to=settings.AUTH_USER_MODEL, verbose_name='Web Link User'),
        ),
    ]
