# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180122_2213'),
        ('invoices', '0007_auto_20171210_0055'),
    ]

    operations = [
    ]
