# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0002_copyrightinfringement_copyrightinvestigation'),
        ('invoices', '0008_merge_20180225_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslogoinvoice',
            name='business_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusinessLogo', to='user.BusinessLogo'),
        ),
        migrations.AddField(
            model_name='businesslogoinvoice',
            name='logo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_viewer_user', to=settings.AUTH_USER_MODEL, verbose_name='Business Logo User'),
        ),
        migrations.AddField(
            model_name='businesslogoinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_logo_user', to=settings.AUTH_USER_MODEL, verbose_name='Business Logo Visitor'),
        ),
        migrations.AddField(
            model_name='embedinvoice',
            name='embed_ski',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skigit.VideoDetail'),
        ),
        migrations.AddField(
            model_name='embedinvoice',
            name='skigit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skigit_embed_user', to=settings.AUTH_USER_MODEL, verbose_name='Skigit User'),
        ),
        migrations.AddField(
            model_name='embedinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embed_business_user', to=settings.AUTH_USER_MODEL, verbose_name='Business User'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='plugin_ski',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ski', to='skigit.VideoDetail', verbose_name='Plugged Skigit'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='primary_ski',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug_ski', to='skigit.VideoDetail', verbose_name='Skigit'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='skigit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skigit_plugin_user', to=settings.AUTH_USER_MODEL, verbose_name='Skigit Logo User'),
        ),
        migrations.AddField(
            model_name='plugininvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_plugin_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='logo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_logo_user', to=settings.AUTH_USER_MODEL, verbose_name='Logo User'),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='post_ski',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skigit.VideoDetail'),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_post_user', to=settings.AUTH_USER_MODEL, verbose_name='Post User'),
        ),
        migrations.AddField(
            model_name='shareinvoice',
            name='share_ski',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skigit.VideoDetail'),
        ),
        migrations.AddField(
            model_name='shareinvoice',
            name='skigit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skigit_share_user', to=settings.AUTH_USER_MODEL, verbose_name='Skigit User'),
        ),
        migrations.AddField(
            model_name='shareinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_share_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]

