# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20180924_1744'),
        ('invoices', '0002_auto_20180517_1852'),
    ]

    operations = [
    ]
