# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-11 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0011_auto_20181119_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='invoicebilling',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_billing', to='invoices.Invoice', verbose_name='Invoice Vault'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicebilling',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
