# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0001_initial'),
    ]
    operations = [
    ]
