# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skigit', '0004_auto_20190808_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightinfringement',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Under investigation'), (3, 'Remove Skigit'), (2, 'Accept Skigit')], default=0, null=True, verbose_name='Investigation Status'),
        ),
        migrations.AlterField(
            model_name='inappropriateskigit',
            name='status',
            field=models.CharField(choices=[('2', 'Under Investigation'), ('4', 'Remove Skigit'), ('3', 'Accept Skigit')], default='2', max_length=20, verbose_name='Status'),
        ),
    ]
