# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skigit', '0005_auto_20200511_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='file_on_server',
            field=models.FileField(help_text='Temporary file on server for using in `direct upload` from your server to youtube', null=True, upload_to='videos/temp'),
        ),
    ]
