# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skigit', '0006_auto_20200728_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightinfringement',
            name='zip_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
