# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skigit', '0007_auto_20200826_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='receive_donate_sperk',
            field=models.IntegerField(choices=[(1, 'Receive sperk'), (2, 'Donate sperk')], default=0, verbose_name='Sperk choice'),
        ),
    ]
