# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skigit', '0008_auto_20210202_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videodetail',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
