# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='receive_donate_sperk',
            field=models.IntegerField(choices=[(2, 'Receive sperk'), (1, 'Donate sperk')], default=0, verbose_name='Sperk choice'),
        ),
    ]
