# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0001_initial'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsharethumbnail',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='social_share_thumbnails', to='skigit.Video'),
            preserve_default=True,
        ),
    ]
