# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20180517_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('2', 'Remove friend'), ('0', 'Pending'), ('3', 'Not a Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('0', 'Pending')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
