# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0006_auto_20170505_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='brochureblogo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='brochureblogo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='embed',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='embed',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='friend',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='friend',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='invitemessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='invitemessage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='posterbusinesslogo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='posterbusinesslogo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='socialsharethumbnail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='socialsharethumbnail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='wallposter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='wallposter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='header_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Header Text'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='poster_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/skigit/brochure/', verbose_name='Brochure'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='brochureblogo',
            name='b_logo',
            field=models.URLField(blank=True, null=True, verbose_name='Business Logo'),
        ),
        migrations.AlterField(
            model_name='brochureblogo',
            name='brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.Brochure', verbose_name='Brochure'),
        ),
        migrations.AlterField(
            model_name='brochureblogo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='brochureblogo',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='brochureblogo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Business User'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='embed_count',
            field=models.IntegerField(default=0, verbose_name='Embed Count'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='embed_type',
            field=models.CharField(choices=[('1', 'External'), ('0', 'Internal')], default='0', max_length=5, verbose_name='Embed Type'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_from_user', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='skigit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_video_id', to='skigit.Video', verbose_name='Skigit'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_to_user', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Friends'), ('2', 'Remove friend'), ('3', 'Not a Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserInvitation', to=settings.AUTH_USER_MODEL, verbose_name='Invited by User'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='invite_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.InviteMessage', verbose_name='Invite Message'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='invited_date',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Invitation Date'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Is Skigit Member'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='to_user_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='invitemessage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='invitemessage',
            name='invite_message',
            field=models.TextField(blank=True, null=True, verbose_name='Invite Message'),
        ),
        migrations.AlterField(
            model_name='invitemessage',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationSenderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Deleted by User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read by User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Viewed by User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='msg_type',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Message Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='skigit_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skigit_id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='posterbusinesslogo',
            name='b_logo',
            field=models.URLField(blank=True, null=True, verbose_name='Business Logo'),
        ),
        migrations.AlterField(
            model_name='posterbusinesslogo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='posterbusinesslogo',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='posterbusinesslogo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Business User'),
        ),
        migrations.AlterField(
            model_name='posterbusinesslogo',
            name='wall_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.WallPoster', verbose_name='Wall Poster'),
        ),
        migrations.AlterField(
            model_name='socialsharethumbnail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='socialsharethumbnail',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Content 1'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='Content 2'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='content3',
            field=models.TextField(blank=True, null=True, verbose_name='Content 3'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='content4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Skigit URL'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='footer_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Footer Text'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/skigit/brochure'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='header_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Header Text'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='poster_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/skigit/brochure/', verbose_name='Wall Poster 18"x24"'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='poster_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/skigit/brochure/', verbose_name='Wall Poster 24"x36"'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='skigit_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/skigit/brochure/', verbose_name='Skigit Logo'),
        ),
        migrations.AlterField(
            model_name='wallposter',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date'),
        ),
    ]
