# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20180924_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('3', 'Not a Friends'), ('2', 'Remove friend'), ('0', 'Pending'), ('1', 'Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
