# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0018_auto_20180925_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('3', 'Not a Friends'), ('1', 'Friends'), ('2', 'Remove friend')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
