# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0019_auto_20180925_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='embed_type',
            field=models.CharField(choices=[('0', 'Internal'), ('1', 'External')], default='0', max_length=5, verbose_name='Embed Type'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('2', 'Remove friend'), ('3', 'Not a Friends'), ('1', 'Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
