# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0029_auto_20181005_2019'),
        ('friends', '0005_auto_20180517_1911'),
    ]

    operations = [
    ]
