# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0030_merge_20181006_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('0', 'Pending'), ('2', 'Remove friend'), ('3', 'Not a Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('0', 'Pending')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
