# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0039_auto_20200728_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='embed_type',
            field=models.CharField(choices=[('0', 'Internal'), ('1', 'External')], default='0', max_length=5, verbose_name='Embed Type'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('0', 'Pending'), ('3', 'Not a Friends'), ('2', 'Remove friend')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='status',
            field=models.CharField(choices=[('1', 'Friends'), ('0', 'Pending')], default='0', max_length=5, verbose_name='Status'),
        ),
    ]
