# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0042_auto_20210202_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='embed_type',
            field=models.CharField(choices=[('0', 'Internal'), ('1', 'External')], default='0', max_length=5, verbose_name='Embed Type'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('3', 'Not a Friends'), ('0', 'Pending'), ('1', 'Friends'), ('2', 'Remove friend')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='skigit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skigit.Video'),
        ),
    ]
