# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-08 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0008_auto_20210202_1357'),
        ('friends', '0043_auto_20210508_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='skigit_id',
            new_name='skigit',
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('3', 'Not a Friends'), ('0', 'Pending'), ('2', 'Remove friend'), ('1', 'Friends')], default='0', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterIndexTogether(
            name='notification',
            index_together=set([('skigit', 'user', 'from_user', 'is_view', 'is_active')]),
        ),
    ]
