# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_template', models.TextField(blank=True, null=True)),
                ('is_html', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('template_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_text',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text',
        ),
    ]
