# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 21:27
from __future__ import unicode_literals

from django.db import migrations
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0002_auto_20180924_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(default='<h1></h1>'),
            preserve_default=False,
        ),
    ]
