# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0003_auto_20180924_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
