# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0004_auto_20180925_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_template', models.TextField(blank=True, null=True)),
                ('template_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='templateheader',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='templateheader',
            name='is_text',
        ),
    ]
