# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0006_auto_20180925_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbody',
            name='is_html',
        ),
    ]
