# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0009_remove_emailtemplate_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailpost.EmailHost'),
            preserve_default=False,
        ),
    ]
