# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0010_auto_20180925_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhost',
            name='host_name',
            field=models.CharField(default='Video', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
