# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0011_emailhost_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
