# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0013_auto_20180925_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhost',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
