# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('status', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow/Unfollow Skigit',
                'verbose_name_plural': 'Follow/Unfollow Skigits',
            },
        ),
        migrations.CreateModel(
            name='Plugged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('plugged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_plugged', to=settings.AUTH_USER_MODEL)),
                ('skigit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skigit.Video')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugging_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite/Unfavorite Skigit',
                'verbose_name_plural': 'Favorite/Unfavorite Skigits',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('social_site', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('skigit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_video_id', to='skigit.VideoDetail', verbose_name='Skigit id')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_to_user', to=settings.AUTH_USER_MODEL, verbose_name='To User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_from_user', to=settings.AUTH_USER_MODEL, verbose_name='From User')),
            ],
            options={
                'verbose_name': 'Share Skigit',
                'verbose_name_plural': 'Share Skigits',
            },
        ),
        migrations.AlterIndexTogether(
            name='share',
            index_together=set([('skigit_id', 'user', 'to_user', 'is_active')]),
        ),
        migrations.AlterIndexTogether(
            name='plugged',
            index_together=set([('skigit', 'user', 'plugged')]),
        ),
    ]
