# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_auto_20171129_2339'),
    ]

    operations = [
    ]
