# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skigit', '0002_copyrightinfringement_copyrightinvestigation'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('plugged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_plugged', to=settings.AUTH_USER_MODEL)),
                ('skigit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skigit.Video')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugging_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite/Unfavorite Skigit',
                'verbose_name_plural': 'Favorite/Unfavorite Skigits',
            },
        ),
        migrations.AlterIndexTogether(
            name='plugged',
            index_together=set([('skigit', 'user', 'plugged')]),
        ),
    ]
