# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_type',
            field=models.CharField(blank=True, choices=[('web', 'Website'), ('ios', 'IOS'), ('android', 'Android')], default='web', max_length=10),
        ),
    ]
